version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: book_api_mongodb
    restart: unless-stopped
    command: ["mongod", "--wiredTigerCacheSizeGB", "1.5"]
    env_file:
      - .env
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    networks:
      - book_network

  mongo_express:
    image: mongo-express:1.0.0
    container_name: book_api_mongo_express
    restart: unless-stopped
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}

      ME_CONFIG_BASICAUTH: "true"
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_BASIC_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_BASIC_PASSWORD}
    depends_on:
      - mongodb
    networks:
      - book_network

  web:
    build: .
    container_name: book_api
    restart: unless-stopped
    volumes:
      - ./backend:/backend
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - book_network
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --workers 2 --timeout-keep-alive 30
    expose:
      - "8000"

volumes:
  mongodb_data:

networks:
  book_network:
    driver: bridge
